const $ = id => document.getElementById(id);
let overview, dataset='reconciliation', page=1, sequence=0, loading=false;
const labels={reconciliation:'Reconciliation records',funding:'Funding ledger',payouts:'Bank payouts',exceptions:'Payment exceptions',monthly:'Month-end reports',quarantine:'Quarantined records'};
const preferred={reconciliation:['record_id','vendor_id','event_date','net_payable','paid_amount','variance','status','last_settlement_date'],exceptions:['record_id','vendor_id','event_date','net_payable','paid_amount','variance','status'],funding:['record_id','vendor_id','event_date','gross_sales','eligible_sales','total_deductions','total_credits','net_payable'],payouts:['payout_id','record_id','vendor_id','event_date','amount','reversal_of'],monthly:['accounting_month','vendor_id','currency','status','record_count','expected_amount','paid_amount','variance'],quarantine:['source_type','quality_errors','raw_record']};
const number=value=>Number(value||0).toLocaleString('en-IN');
const money=value=>value===null?'—':Number(value).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
const title=key=>key.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
function notice(text){$('notice').hidden=!text;$('notice').textContent=text||'';}
async function api(path){const response=await fetch(path,{cache:'no-store'});const data=await response.json();if(!response.ok){const error=new Error(data.error||'Request failed');error.status=response.status;throw error;}return data;}
function metric(label,value,note){const card=node('div',undefined,'metric');card.append(node('div',label,'metric-label'),node('div',value,'metric-value'),node('div',note,'metric-note'));return card;}
function renderOverview(data){
 $('subtitle').textContent=`As of ${data.as_of} · Published ${new Date(data.completed_at).toLocaleString()} · ${data.source_partitions.length} source date${data.source_partitions.length===1?'':'s'}`;
 $('metrics').replaceChildren(metric('Funding records',number(data.counts.gold_funding),'Validated, current record versions'),metric('Matched payments',number(data.statuses.MATCHED||0),'Expected funding equals bank settlement'),metric('Open exceptions',number(data.counts.exceptions),'Includes reversals, contra and orphan payouts'),metric('Expected funding',money(data.totals.expected),`Bank settlements: ${money(data.totals.paid)}`));
 $('outcomes').replaceChildren();const total=data.counts.gold_reconciliation;
 for(const [status,count] of Object.entries(data.statuses).sort((a,b)=>b[1]-a[1])){const row=node('div',undefined,'outcome');row.dataset.status=status;const track=node('div',undefined,'track'),bar=node('div',undefined,'bar');bar.style.width=`${Math.max(1,100*count/Math.max(total,1))}%`;track.append(bar);row.append(node('span',title(status)),track,node('strong',number(count)));$('outcomes').append(row);}
 $('gate').textContent=`Quality gates ${data.quality_gates.checks.toLowerCase()}`;$('gate').className='pass';
 const rejected=Object.values(data.quality).reduce((n,q)=>n+q.quarantined,0),duplicate=Object.values(data.quality).reduce((n,q)=>n+q.duplicate_versions,0);
 $('quality').replaceChildren();for(const [label,value] of [['Rejected source records',number(rejected)],['Superseded versions',number(duplicate)],['Exception ratio',`${(data.quality_gates.exception_ratio*100).toFixed(2)}% / ${(data.quality_gates.policy.max_exception_ratio*100).toFixed(0)}% limit`],['Processing duration',`${data.elapsed_seconds.toFixed(1)} seconds`],['Ledger variance',money(data.totals.variance)]]){const row=node('div',undefined,'quality-row');row.append(node('span',label),node('strong',value));$('quality').append(row);}
 $('lineage').textContent=`Run: ${data.run_id}\nPolicy: ${data.policy_version}\nSource dates: ${data.source_partitions.join(', ')}\n\nSource SHA-256 hashes\n${Object.entries(data.inputs).map(([k,v])=>`${k}: ${v}`).join('\n')}`;
 const oldStatus=$('status').value,oldVendor=$('vendor').value;
 $('status').replaceChildren(new Option('All statuses',''),...Object.keys(data.statuses).sort().map(s=>new Option(title(s),s)));
 $('vendor').replaceChildren(new Option('All vendors',''),...data.vendors.filter(Boolean).map(v=>new Option(v,v)));
 $('status').value=oldStatus;$('vendor').value=oldVendor;
}
async function refresh(force=false){if(loading)return;loading=true;$('refresh').disabled=true;try{const next=await api('/api/summary');const changed=!overview||overview.run_id!==next.run_id;overview=next;renderOverview(next);notice('');if(changed||force){if(changed){page=1;$('detail').close();}await loadTable();}}catch(error){notice(error.message);if(!overview){$('tbody').replaceChildren(node('tr'));$('tbody').firstChild.append(node('td','No results published yet. Complete a pipeline run in Airflow, then refresh.','empty'));}}finally{loading=false;$('refresh').disabled=false;}}
async function loadTable(){if(!overview)return;const request=++sequence,selected=dataset;
 $('table-title').textContent=labels[dataset];$('status').disabled=!['reconciliation','exceptions','monthly'].includes(dataset);$('vendor').disabled=dataset==='quarantine';
 const args=new URLSearchParams({dataset,page,size:25,run_id:overview.run_id,search:$('search').value,status:$('status').disabled?'':$('status').value,vendor_id:$('vendor').disabled?'':$('vendor').value});
 try{const data=await api('/api/table?'+args);if(request!==sequence||selected!==dataset)return;notice('');const cols=preferred[dataset].filter(c=>data.columns.includes(c));$('thead').replaceChildren();const head=node('tr');cols.forEach(c=>head.append(node('th',title(c))));$('thead').append(head);$('tbody').replaceChildren();
 for(const row of data.rows){const tr=node('tr');for(const col of cols){const cell=node('td');if(col==='record_id'&&row[col]){const button=node('button',row[col],'record-link');button.addEventListener('click',()=>showRecord(row[col]));cell.append(button);}else if(col==='status'){cell.append(node('span',title(row[col]),`badge ${row[col]}`));}else if(['net_payable','paid_amount','variance','amount','gross_sales','eligible_sales','total_deductions','total_credits','expected_amount'].includes(col)){cell.textContent=money(row[col]);}else{cell.textContent=row[col]===null?'—':String(row[col]);}tr.append(cell);}$('tbody').append(tr);}
 if(!data.rows.length){const tr=node('tr'),td=node('td','No records match these filters.','empty');td.colSpan=cols.length;tr.append(td);$('tbody').append(tr);}
 $('row-count').textContent=`${number(data.total)} records`;$('page-label').textContent=`Page ${page} of ${Math.max(1,Math.ceil(data.total/25))}`;$('prev').disabled=page===1;$('next').disabled=page*25>=data.total;
 }catch(error){if(request!==sequence)return;notice(error.message);if(error.status===409)refresh(true);}
}
async function showRecord(id){try{const data=await api('/api/record?'+new URLSearchParams({record_id:id,run_id:overview.run_id}));$('detail-title').textContent=id;$('detail-body').replaceChildren();for(const [name,rows] of [['Reconciliation',data.reconciliation],['Funding calculation',data.funding],['Bank payments',data.payouts]]){const section=node('section',undefined,'detail-section');section.append(node('h2',name));if(!rows.length)section.append(node('p',name==='Bank payments'?'No bank payments found for this funding record.':'No record in this dataset.'));for(const row of rows){const grid=node('div',undefined,'detail-grid');for(const [key,value] of Object.entries(row)){if(['run_id','source_file','policy_version'].includes(key))continue;const field=node('div',undefined,'detail-field');field.append(node('small',title(key)),node('strong',value===null?'—':Array.isArray(value)?value.join(', '):String(value)));grid.append(field);}section.append(grid);}$('detail-body').append(section);}$('detail').showModal();}catch(error){notice(error.message);if(error.status===409)refresh(true);}}
for(const button of document.querySelectorAll('.nav'))button.addEventListener('click',()=>{document.querySelector('.nav.active').classList.remove('active');button.classList.add('active');dataset=button.dataset.dataset;page=1;$('search').value='';$('status').value='';$('vendor').value='';loadTable();});
$('refresh').addEventListener('click',()=>refresh(true));$('apply').addEventListener('click',()=>{page=1;loadTable();});$('search').addEventListener('keydown',e=>{if(e.key==='Enter'){page=1;loadTable();}});$('prev').addEventListener('click',()=>{page--;loadTable();});$('next').addEventListener('click',()=>{page++;loadTable();});$('close').addEventListener('click',()=>$('detail').close());setInterval(()=>{if($('auto').checked)refresh();},15000);refresh(true);
