FROM apache/airflow:2.10.5-python3.11
USER root
RUN apt-get update && apt-get install -y --no-install-recommends openjdk-17-jre-headless && rm -rf /var/lib/apt/lists/* && mkdir -p /opt/airflow/data && chown airflow:root /opt/airflow/data
USER airflow
COPY --chown=airflow:root pyproject.toml /opt/retail/pyproject.toml
COPY --chown=airflow:root src /opt/retail/src
RUN pip install --no-cache-dir "apache-airflow==2.10.5" "/opt/retail[spark]"
ENV SPARK_LOCAL_IP=127.0.0.1

COPY --chown=airflow:root dags /opt/airflow/dags
